service: personal-expense
frameworkVersion: "3"
useDotenv: true

custom:
  region: ${opt:region}
  accountId: ${aws:accountId}

provider:
  name: aws
  runtime: python3.11

package:
  individually: true
  patterns:
    - "!*/**"

layers:
  DynamoDB:
    description: DynamoDB layer of personal expenses
    compatibleArchitectures:
      - x86_64
    retain: false
    allowedAccounts:
      - "*"
    package:
      artifact: layers/zip-files/DynamoDBLambdaLayer.zip

functions:
  createExpense:
    handler: create-expense.handler
    layers:
      - { Ref: DynamoDBLambdaLayer }
    role: createExpenseRole
    package:
      individually: true
      patterns:
        - "./create-expense.py"
    events:
      - httpApi:
          path: /expense
          method: post

resources:
  Resources:
    personalExpenseDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: personal_expenses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: date
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: category_name_index
            KeySchema:
              - AttributeName: date
                KeyType: HASH
              - AttributeName: category
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    createExpenseRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: createExpenseRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: createExpenseConnectDynamodb
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:BatchGet*"
                    - "dynamodb:DescribeStream"
                    - "dynamodb:DescribeTable"
                    - "dynamodb:Get*"
                    - "dynamodb:Query"
                    - "dynamodb:Scan"
                    - "dynamodb:BatchWrite*"
                    - "dynamodb:CreateTable"
                    - "dynamodb:Delete*"
                    - "dynamodb:Update*"
                    - "dynamodb:PutItem"
                  Resource: "arn:aws:dynamodb:${self:custom.region}:${self:custom.accountId}:table/personal_expenses"
